version: "3.8"

services:
  postgres16:
    image: postgres:16
    container_name: postgres16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    volumes:
      - ./postgres16:/var/lib/postgresql/data
    networks:
      - postgres16
    restart: always

networks:
  postgres16:
